name: CI/CD Pipeline for Terraform

on:
  push:
    branches:
      - main   # This triggers the pipeline whenever you push to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest   # The OS for the GitHub runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This action checks out your repository's code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1  # This sets up Terraform on the GitHub runner
        with:
          terraform_version: '1.0.0'  # You can change this to any version you prefer

      - name: Terraform Init
        run: terraform init  # This initializes the Terraform configuration

      - name: Terraform Plan
        run: terraform plan  # This shows what Terraform will do without applying changes

      - name: Terraform Apply
        run: terraform apply -auto-approve  # This applies the Terraform configuration automatically
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   # AWS credentials stored in GitHub secrets
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'  # You can change this to the region you use
- name: Set up AWS Credentials
  uses: aws-actions/configure-aws-credentials@v1
  with:
    aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Set this in GitHub Secrets
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Set this in GitHub Secrets
    aws_region: ${{ secrets.AWS_DEFAULT_REGION }}  # Optional, specify the region like us-east-1
